### ISSUE TITLE
Ansible lint errors

### ISSUE THREAD

**Issue by weehal** [weareinteractive/ansible-sudo#20]
When I run `ansible-lint` on this role I get 3 errors. Two of them are in `meta/readme.yml`
I wonder if this file is used for something more than information and can be renamed to readme.md?

1. `[701] No 'galaxy_info' found`
1. `[204] Lines should be no longer than 160 chars`

The third error is resolved in proposed PRs - #18 (cosmetic change) or #19

**Comment by franklinkim** [comment]
Nr 1 & 2. should be fixed with 555208efc6b0baf2773e649f1aea0e575abf3516
