### ISSUE TITLE
failing ansible container build with 1.12.2 release

### ISSUE THREAD

**Issue by sophie-la-li** [weareinteractive/ansible-sudo#21]
Hi there,

our ansible container build fails with the following error using the latest 1.12.2 release. Downgrade to 1.12.0 fixed the problem. I'm still looking for the exact reason atm but i'm not experienced in this roles source code. We use centos:latest as conductor image, ansible version 2.4.3.0 and ansible container version 0.9.2.

`TASK [weareinteractive.sudo : Remove unmanaged /etc/sudoers.d/ files] **********
task path: /etc/ansible/roles/weareinteractive.sudo/tasks/config.yml:20
fatal: [app]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure in finding the lookup named '{{ sudoers_contents.files }}' in the available lookup plugins"
}
	to retry, use: --limit @/tmp/tmpCOujGw/playbook.retry
`

**Comment by franklinkim** [comment]
Hi, seems it's due to the older ansible version.
Tests are running with 2.7 and succeed. Could pin it down exactly but it seems to be sth with the loop and some changed occurred on > 2.5.

**Comment by sophie-la-li** [comment]
Okay. Thank you for the clarification. I think this issue is "solved" with https://github.com/weareinteractive/ansible-sudo/commit/df85f2e26ca9ef2b63337f3a9423f7730f2841be . I will test with an upgraded ansible as soon as i can.
