### ISSUE TITLE
Ansible 2.8.0 deprecation warnings

### ISSUE THREAD

**Issue by mcg** [weareinteractive/ansible-sudo#24]
Just a heads up. Getting some deprecation warning with 2.8.0:

`[DEPRECATION WARNING]: evaluating purge_other_sudoers_files as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see
CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

**Comment by crazikPL** [comment]
PR #22 should address this..
