### ISSUE TITLE
visudo not in PATH in Debian 10

### ISSUE THREAD

**Issue by debuglevel** [weareinteractive/ansible-sudo#25]
As far as I know, /usr/sbin/ is not in the PATH anymore in Debian 10 for regular users. Hence, the call to `visudo` fails, although it is available as `/usr/sbin/visudo`.

`fatal: [172.23.50.246]: FAILED! => {"changed": false, "checksum": "911203c5a64220a807e529e2bb53ffee9b2b6218", "cmd": "visudo -cf /home/tux/.ansible/tmp/ansible-tmp-1563060757.75-52386768038095/source", "msg": "[Errno 2] No such file or directory", "rc": 2}`

**Comment by franklinkim** [comment]
Hi, just ran it on Debian 10 and it passes. I do run the role with `become: yes` (see `tests/main.yml)`
