### ISSUE TITLE
Error while purging non manages files

### ISSUE THREAD

**Issue by pablogmorales** [weareinteractive/ansible-sudo#26]
Hello,
Im, getting this error even though with the example provided on ansible galaxy
---

- hosts: mdo
  become: yes
  roles:
    - weareinteractive.sudo
  vars:
    sudo_defaults:
      - defaults: env_reset
      - defaults: secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - name: 'user1'
        defaults: 'requiretty'
      - name: '%group1'
        defaults: '!requiretty'
    sudo_users:
      - name: 'user1'
      - name: 'user2'
        nopasswd: yes
      - name: '%group1'
        hosts: 127.0.0.1
      - name: '%group2'
        commands: '/bin/ls'
      - name: '%group3'
        commands:
          - '/usr/bin/ls'
          - '/usr/bin/df'
          - '/usr/bin/mailq'
      - name: '%group4'
        users: 'user1,user2'
        groups: 'group1,group2'
    purge_other_sudoers_files: yes

TASK [weareinteractive.sudo : Remove unmanaged /etc/sudoers.d files] **************************************************************************************************
fatal: [mdo]: FAILED! => {"msg": "Unexpected failure in finding the lookup named '{{ sudoers_contents.files }}' in the available lookup plugins"}

ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Any help?
Thanks
Regards

**Comment by pablogmorales** [comment]
Nevermind, sorry for the noise, updating to 2.8 the erros is gone..

**Comment by pablogmorales** [comment]
Is there a way to have this configuration? I just want users to execute ome command with specific users.

user ALL=(tomcat8) NOPASSWD: instead of ALL ?

Thanks

**Comment by franklinkim** [comment]
hi, not quite getting what you want to do... maybe sth like:

```yaml
- name: 'user'
  users: 'tomcat8'
  nopasswd: yes
  commands:
    - '/bin/ls'
```

**Comment by pablogmorales** [comment]
That's it, thank you!

**Comment by franklinkim** [comment]
welcome
