### ISSUE TITLE
Specify user on which i can use sudo

### ISSUE THREAD

**Issue by PlugIN73** [weareinteractive/ansible-sudo#5]
Hi!
In 1.0.0 version I see this:
https://github.com/weareinteractive/ansible-sudo/blob/1.0.0/templates/etc-sudoers-d-ansible.j2#L4
.. ALL=(**ALL**) ..
How can i specify this in latest version? May i send pull request with this feature?

**Comment by franklinkim** [comment]
Sure, send me! I'll look it over and merge!
