### ISSUE TITLE
Convert to module

### ISSUE THREAD

**Issue by colin-byrne-1** [weareinteractive/ansible-sudo#8]
Hey, I am fairly new to Ansible, but I am just wondering if there's any reason this couldn't all be converted to a module instead of a role? Would seem a good bit more tidy... Thanks!

**Comment by franklinkim** [comment]
Hi, yes, actually you could create a module that manages i.e. a file under `/etc/sudoers.d` thus making the template obsolete but in the end, this role would still wrap that module in a way to be able to manage these entries through a yml variable.
