### ISSUE TITLE
Unable to specify run as group parameter

### ISSUE THREAD

**Issue by l3rady** [weareinteractive/ansible-sudo#9]
Take the following sudoers entries:

```
# User privilege specification
deploy    ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
```

the second param in the bracket allows a user/group to use `sudo -g` to set their group membership for the run command.

**Comment by l3rady** [comment]
Thank you for the speedy fix!

**Comment by franklinkim** [comment]
your welcome! if sth doesn't work, let me know (and PRs are welcome too :)!
